[misc]
assume_yes = true     # Don't ask for confirmation before each step

# Disable these steps
disable = [           # Disable the following
    # "system",       # System software update
    # "brew",
    # "shell",        # e.g. oh-my-zsh
    "miktex",         # MikTeX
]

# Only run these steps, ignoring everything else (alternative to `disable`)
# only = ["brew", "commands"]

# ignore_failures = ["commands"]

cleanup = true        # Cleanup caches and old packages after updates finish

[brew]
greedy_cask = true
autoremove = true

[commands]            # Custom commands
# "Update MiKTeX" = "mpm --update" # Custom update command for miktex packages
"Brew cleanup" = "brew cleanup --prune=all"

